### ISSUE TITLE
OVC Performance

### ISSUE THREAD

**Issue by mbt28** [tomaskovacik/hw#1]
Hello,

I am designing a CDC Emulator for an other car using OVC3860, I found your page while I was looking OVC3860 lib for Kicad. 

What are your experiences with OVC3860? Does it make ground loop? Cracks or hums? Should I use pre-amplifier. I will be very glad if you can share your experiences because there are not so much information about designing a circuit with this chip unit. 

Regards.

**Comment by tomaskovacik** [comment]
hi, it has diferencial output, so use dif preamp with proper gain, and
it will work, I'm currently designing s3860m-s cdc module, I put here on
github, work in progress :)

https://github.com/tomaskovacik/hw/tree/master/kicad/arduino_based_cdc_emulator/atmegax8_with_bluetooth

t.

**Comment by mbt28** [comment]
Thank you for your reply, but how ARESET and BTReset communicates here?

**Comment by tomaskovacik** [comment]
Just reset delays. To proper restart bt and arduino after start.

Sent from my Sony Xperia™ smartphone

---- mbt28 wrote ----

**Comment by mbt28** [comment]
I was checking your library for the OVC3860 but the pinout pretty different than that I saw on the internet. I will check it out once I go home how many pins I have with it but  your schematics even have different number of legs on left and right side.

Why are there a difference like that? Mine was OVC3860 version 3.0.

**Comment by tomaskovacik** [comment]
S3860m-s is module, no xs3868. I ordered 3times xs module but always this typebof module came. Look at fordacp hw part, there are photosbof module, top-back sitlde with part number

Sent from my Sony Xperia™ smartphone

---- mbt28 wrote ----

**Comment by mbt28** [comment]
I seee, I didnt know that this kind of module exist. I checked it`s datasheet, seems like it is the same just with few more pins. Is there any difference in practise?

**Comment by tomaskovacik** [comment]
Not really, just cant get it to change name :( desoldering eeprom and rewrite bt device name is required in external programer.... Just this, but it really sucks :D

Sent from my Sony Xperia™ smartphone

---- mbt28 wrote ----

**Comment by mbt28** [comment]
Yeah, I saw it on internet that some guys were changing binary code to rename the device. But if you want to change the password you can change it with pskeys tool, http://www.mikrocontroller.net/attachment/261351/OVC3860_RevE_PSKeys_Setting_v1.2.pdf

Could you please explain me why do we need differential preamp?

**Comment by tomaskovacik** [comment]
cose output is diferential? :) look for datasheet for module, common 
audio pin is 0.9V offset to GND. it works with headphones, also it works 
if you put caps on all 3 audio pins, but signal is so low, that you need 
set volume to highest level and then all noise is also amplified, or 
thies are my observations.

t.

**Comment by mbt28** [comment]
I see. Have you had any experiences with mp3 and aac? Because some say it has internal mp3 and aac codec and some say it has only standart sbc codec.

**Comment by tomaskovacik** [comment]
do not have, also I do not care :D

how can I change bt name? I cant find it its localname PSKEY?

if so, its just rs232 komunication (if I understande correctly:Connect 
the OVC3860 Uart to windows PC by COM1 interface), so, just sniff it and 
implemented in arduino

**Comment by tomaskovacik** [comment]
ok, so I successfully use revD tool: https://github.com/tomaskovacik/hw/blob/master/kicad/library/datasheet/OVC3860_revd_config_tool.exe to set baudrate to 9600 and change name to "AUDI CHORUS"

but I do not have 2 usb-serial modules capable of 115200b (just ch340 arduinos uncapable of 115200b :D, so sniffing must wait till I get to work

thx for tip!

**Comment by mbt28** [comment]
The thing that I dont understand is how do you calculate pre amplification? Also I am planning to build a bluetooth speaker which needs 15W+15W power, where can I start?

Is it important to feed the amplifier with 5V or 3.6V or 12V?

Thank you.

**Comment by tomaskovacik** [comment]
google is your friend ;) http://www.daycounter.com/Calculators/Op-Amp/Op-Amp-Voltage-Calculator.phtml

you can also buy complete module with poweramp

**Comment by josb86** [comment]
Hi tomaskovacik I have this module the pins 44 and 43 are rt and tx [https://36.media.tumblr.com/d6927161e138348750edb44f577a106a/tumblr_inline_ntxj750Vk01qz5qdm_540.png](url). Whit you program, and only conecting this module to a usb to ttl like this [http://www.haoyuelectronics.com/Attachment/CP2102_module/CP2102_3.jpg](url) I can change te name of this module?

**Comment by tomaskovacik** [comment]
http://kovo-blog.blogspot.sk/2016/01/ovc3860-how-to-change-name.html ;)

**Comment by Arktorus** [comment]
Hi, could you please make it so that the COM port used in the XS3868 PSKey Tool is user chosen? It will solve a lot of problem for me, and perhaps, many others.

**Comment by tomaskovacik** [comment]
in program made by omnivision?

**Comment by Arktorus** [comment]
Sorry I didn't understand it wasn't made by you. My RX TX communication is running fine when checking with the arduino serial monitor. 


![image](https://cloud.githubusercontent.com/assets/13820900/21586203/1db9c1c8-d0f4-11e6-9bc1-a78f727489a0.png)


But seemingly, even after it shows connected in the RevD PSKeys tool, it doesn't read the values, but instead, shows a (presumably) error message in some language unknown to me.

![image](https://cloud.githubusercontent.com/assets/13820900/21586228/71dd8a8c-d0f4-11e6-9e11-3188a3e0399c.png)

**Comment by tomaskovacik** [comment]
strange, did you use arduino as usb to  serial interface ? Or which usb to serial adapter did you use? based on which chip?

**Comment by Arktorus** [comment]
Please note that I did the COM1 assignment to the USB TTL dongle without disabling HW COM1 separately, could that be making a difference? I don't even know what the approach for doing that is?
Thanks for replying!

**Comment by Arktorus** [comment]
No, I have both USB-TTL dongle (which works as shown in the two pictures) and an Arduino (which had been successfully used for communication earlier). I am trying this on the XS3868 module (which appear from your previous comments to be a variant of the s-3860m-s, I have also been in limited contact with the manufacturers of the chip who refer to it by this name).

**Comment by tomaskovacik** [comment]
ok, on which chips is your dongle based? I experiences problems at 115kb with CH340 based serial dongles

**Comment by tomaskovacik** [comment]
about HW serial port, look at BIOS if you can disable it there, it can be source of your trouble

**Comment by Arktorus** [comment]
I have a PL2303 based chip (some company called Prolific Tech makes them) They have also kindly provided a chip version checker.

![image](https://cloud.githubusercontent.com/assets/13820900/21586482/99cdf272-d0f7-11e6-8689-21d6e1c613ee.png)

**Comment by tomaskovacik** [comment]
these are fine, so I problem is only HW port, try to disable it. If you cant, only solution I can emagine is disable it in HW manager of windows, uninstall driver for it (if it's posible) or as last, boot some life version of linux and run tool with WINE, where you can set COM1 to any serial interace.

**Comment by Arktorus** [comment]
Hopefully, last update - I tried disabling the Hardware port in BIOS (Lenovo G560), seems they don't really provide any HW COM port manipulation options - just the USB legacy support enabling and disabling. However, I tried once again. did the ground to reset and back routine, and the chip went dark, and n a hunch, pressed read all, and lo!

![image](https://cloud.githubusercontent.com/assets/13820900/21590972/15ca14a4-d126-11e6-99e0-5f9b4bc18480.png)

Still not sure if I can make this work a second time, but yes, thanks to your help, I was able to read! 
Just a minor question, most Bluetooth devices when the call/play/pause button is pressed, opens up Google now/Siri. Does the OVC3860, in your experience, do that?

**Comment by tomaskovacik** [comment]
:), Didn't I wrote thet reset is required after program start? o_O I must forget about it, sorry ;)

**Comment by tomaskovacik** [comment]
you have set avsnk as profile(key n. 7) = bleutooth speaker, so maybe cose that ...

**Comment by AgostinoA** [comment]
Hi...I have a problem,when change name,for example "hello" .
On my device phone in Bluetooth devices show as "AVHS"

**Comment by tomaskovacik** [comment]
push "write all" button ;)

**Comment by gtv31** [comment]
Did that, however, still the same: "AVHS"

**Comment by soldiaz** [comment]
Dear guys, I am glad to found this information!
I would like to rename the ovc 3960 chip but I am totally newbie.

I do face ground loop noise. Is it possible to fix that? And 2nd I would like to rename device's name. Could you kindly describe which part I am supposed to write?

Any help appreciated,
kind regards 
Soldiaz

**Comment by tomaskovacik** [comment]
http://kovo-blog.blogspot.sk/2016/01/ovc3860-how-to-change-name.html

for ground loop noice, never connect audio ground to power supply ground, try plain headphones, if noise is gone, you find problem, for audio output you should use diferencial preamp : https://github.com/tomaskovacik/hw/tree/master/kicad/differencial_audio_amplifier

**Comment by soldiaz** [comment]
Dear tomaskovacik thanks for the very quick answer!

Could you please advise how to wire a cp2102 ? I connected + and ground but do not know how to use d+ and d-. Is it like tx/rx?

Kind regards Soldiaz

**Comment by soldiaz** [comment]
I own a regular USB port...

**Comment by soldiaz** [comment]
Could you please give a hint on howto find tx rx pins on the board which uses ovc3960 chip?

Kind regards

**Comment by tomaskovacik** [comment]
I need a know what board exactly do you have, picture for example, also what cp2102 board you have

t.

**Comment by soldiaz** [comment]
Dear Tomaskovacik, I really appreciate your technical advise. I ordered 5 bt dongles. In fact 3 of them had the OVC3960 chip and 2 of them were based on another one like bentek or something like this. I was not aware of that fact as I thought they all were based on Omnivision...

Fortunately the OVC based ones supplied the ability to connect to rx tx. So i will give it a try!

**Comment by soldiaz** [comment]
I tried to connect to rx tx but had issues with soldering ....meanwhile I found software to program BEKEN bk3254 BT chipset aka BT-163. Available here: 

[http://www30.zippyshare.com/v/m8NFJS1j/file.html]

Even with the ability to solder a mic on it. There are 6 pins which are supposed for UART connections but they are not branded - so I do not know how to connect tx rx.

**Comment by davidferguson** [comment]
@tomaskovacik or @Arktorus Would either of you be able to post screenshots of all the default values read by the software of your chip? I'm curious to see what you have.

**Comment by tomaskovacik** [comment]
https://github.com/tomaskovacik/kicad-library/tree/master/library/datasheet

*.dat files are saved pskeys

**Comment by ansonl** [comment]
@tomaskovacik Does the OVC3860 differential audio output the reversed polarity signal and both Right and Left through a single Audio Ground/Neutral pin? On the BLK-MD-SPK-B and XS3868 module pin outs, I see that there are three pins: Spk Left, Spk Right, and Spk Ground/Neutral. 
If this is not how it works, is the Spk Ground/Neutral pin just a shared ground and other pins carry the reverse polarity signals for right and left? Thanks.

**Comment by tomaskovacik** [comment]
@ansonl hi,

I did not check it with scope, but it is used in example schematic as dif. output:
https://github.com/tomaskovacik/kicad-library/blob/master/library/datasheet/OVC3860_based_modules/BLK-MD-SPK-B_DEMO_MUTE.pdf

so why not use it in the same way
