### ISSUE TITLE
motorola cracker pcb

### ISSUE THREAD

**Issue by kaalis** [tomaskovacik/hw#3]
Hello, maybe you have complete cracker board for sale?
Couldn't find it in tindie.
Got one Blaupunkt concert with motorola chip and unknown pin code.

**Comment by tomaskovacik** [comment]
You can read itin radio

Take look 

http://kovo-blog.blogspot.com/2015/08/audi-chorus-concert-how-to-recover.html

**Comment by kaalis** [comment]
Yes, i read it before asking, but i'm not so good at creating things. Thanks, i will try to find a person who would create it from schematic.

**Comment by tomaskovacik** [comment]
Your really do not need to create anything, you need just 10Volts powersource and solder cables on boardOn 25 Nov 2018 20:49, kaalis <notifications@github.com> wrote:Yes, i read it before asking, but i'm not so good at creating things. Thanks, i will try to find a person who would create it from schematic.

**Comment by tomaskovacik** [comment]
I am closing this, if you want you can order pcb at jlcpcb.com board you are looking for is this one: 

https://github.com/tomaskovacik/hw/tree/master/kicad/motorola_cracker/

download all files, then in kicad open file:  	motorola_cracker.pro and in pcbnew export layers for pcb prototyping based on this how-to:

https://jlcpcb.com/capabilities/Kicad%20PCB%20to%20gerber%20files

but!

this require that you can desolder original mcu from board = you need hot-air gun, then order PCB, components and solder it all together, then you need 12V powersuply (ok this can be car) and serial to USB adapter (cheap one from china will do)

while leaving chip in radio, you need just few resistors and serial to usb converter and you are good to go, it's not stable solution as i mentioned in my post at blog but it will get you stable reading for from eeprom so you can read safe code 

hope this help

sorry for late update I forget about this issue

**Comment by kaalis** [comment]
> you need just 10Volts powersource

Did you mean 12v? Yes, I have PC PSU on my desk.

Could you tell which pin is light blue wire on your converter? Is it ground?
I just ordered serial converter and resistors from Ali, should receive after new year, i think.
![serial-converter](https://user-images.githubusercontent.com/787507/49111171-0a815900-f298-11e8-8a47-d91086063900.jpg)

**Comment by tomaskovacik** [comment]
RtsGreen i ground ,later connected to black wireBut, do not get to complicted from usb2serial adapter you needGroundRxTxRtsEverything else is already in radioRegarding 10V and 12V, yes 12V, some old schematics show 10V but 12V works fineOn 27 Nov 2018 21:57, kaalis <notifications@github.com> wrote:
you need just 10Volts powersource
Did you mean 12v? Yes, I have PC PSU on my desk.
I just ordered serial converter and resistors from Ali, should receive after new year, i think.

Could you tell which pin is light blue wire on converter? Is it ground?

**Comment by kaalis** [comment]
Hello, successfully booted MCU and read dump and desoldered all extra stuff.
You can delete this topic if you like.
Mega thanks for help. :smiley:
